version: '3'
services:
  web:
    build: .
    ports:
     - "5000:5000"
    volumes:
      - ./:/usr/src/app
      - ./node_modules:/usr/src/app/node_modules
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
